# Generated by Django 3.2.2 on 2021-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlotArea', models.IntegerField(max_length=250)),
                ('BuiltUpArea', models.IntegerField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
                ('Amenities', models.CharField(max_length=250)),
                ('Price', models.IntegerField(max_length=250)),
            ],
        ),
    ]
