# Generated by Django 3.2.2 on 2021-05-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HyderabadEstates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villas',
            name='BuiltUpArea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='villas',
            name='PlotArea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='villas',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
